### ISSUE TITLE
Additional environment variables?

### ISSUE THREAD

**Issue by brycewray** [cloudflare/pages-action#10]
What would be the proper way to add more environment variables in the use of this GitHub Action? As a way of comparison, a similar Action for Vercel deployments (https://github.com/BetaHuhn/deploy-to-vercel-action) has an optional `BUILD_ENV` key for inserting these vars, e.g.:

```yaml
      - name: Publish to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_HUGO_SITE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
          WORKING_DIRECTORY: 'public'
          BUILD_ENV: |
            WEBMENTION_IO_TOKEN="${{ secrets.WEBMENTION_IO_TOKEN }}"
```

Is something like that possible with `pages-action`, too? Thanks in advance for any related info you could provide.
