### ISSUE TITLE
"No deployment available" when deploying with this action

### ISSUE THREAD

**Issue by mthenw** [cloudflare/pages-action#122]
Hi, 

my setup is pretty straight-forward. I have a Remix app with a simple build step `remix vite:build`. 

When I run the following commands locally it deploys to Cloudflare successfully. 
```
remix vite:build
npx wrangler@3 pages publish ./build/client --project-name="xxx" --branch="main"
```

but when I use the action (which uses the same command) I get failed deployment with "No deployment available" in the dashboard, even though GH action output says it was successful:

```
✨ Compiled Worker successfully
Uploading... (21/21)
✨ Success! Uploaded 0 files (21 already uploaded) (0.33 sec)

✨ Uploading Functions bundle
✨ Deployment complete! Take a peek over at https://5f466361.xxx-dyu.pages.dev/
```

Is there a way to debug it?

---

publish.yaml:

```
...
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: xxx
          directory: ./build/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
...
```
