### ISSUE TITLE
Add per-branch alias URL to output value

### ISSUE THREAD

**Issue by ngbrown** [cloudflare/pages-action#18]
Currently the only output URL is the unique-per-deployment URL. Each branch also has an alias that could be preferable to visit, especially because of login sessions.

I would combine this with #14 to specify the branch in the case of pull request builds. Because those show up only as `HEAD`, because GitHub is actually building on a test-merge commit.

**Comment by rohit-gohri** [comment]
I think this is still an issue, the output of the example workflow doesn't return the correct alias - https://github.com/cloudflare/pages-action/actions/runs/3631522134/jobs/6126266418#step:4:11

Haven't tested in my repo yet

**Comment by WalshyDev** [comment]
> I think this is still an issue, the output of the example workflow doesn't return the correct alias - [cloudflare/pages-action/actions/runs/3631522134/jobs/6126266418#step:4:11](https://github.com/cloudflare/pages-action/actions/runs/3631522134/jobs/6126266418#step:4:11)
> 
> Haven't tested in my repo yet

That was for production, production doesn't have an alias so it can't return one. What would you expect there?

**Comment by rohit-gohri** [comment]
The main url, https://github-actions-example.pages.dev/ ? Since that is the "alias" for production

**Comment by peschee** [comment]
I am also running into this issue. Given this simple config:

```yaml
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.2.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: xxx
          projectName: yyy
          directory: zzz
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        id: publish
```

I get this alias in these outputs from the action when running in on a branch (e.g. in a PR)

```
ID: 8a8296e1-e646-45ca-9bae-9ed8001c7fb9
URL: https://8a8296e1.xxx.pages.dev
Environment: preview
Alias: https://head.xxx.pages.dev
```

I guess {{head}} is wrong here?

**Comment by peschee** [comment]
Maybe related to #22 ?

**Comment by peschee** [comment]
When I add the `branch` parameter I get the right alias (in a PR):

```yaml
ID: 2640a0f7-9755-4666-b3c7-046b95704a59
URL: https://2640a0f7.xxx.pages.dev
Environment: preview
Alias: https://2640a0f7.xxx.pages.dev
```
