### ISSUE TITLE
Option to disable creation of environment & deployment

### ISSUE THREAD

**Issue by fubhy** [cloudflare/pages-action#30]
We are using the `environment` context in our github workflow to assign a name and url manually. It would be great if it was possible to disable the automatic creation of a deployment and environment and take full control instead, e.g:

```
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 
      name: Preview (PR-${{ github.event.number }})
      url: ${{ steps.publish.outputs.url }}
```
