### ISSUE TITLE
Map deployment to pull request

### ISSUE THREAD

**Issue by peschee** [cloudflare/pages-action#39]
Hi

Is there a way to "map" / assign a deployment to a pull request?

Given this config:

```yaml
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.2.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: xxx
          projectName: yyy
          directory: zzz
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        id: publish
```

We normally get this for our pull requests:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/63866/206641105-fb5f8cd7-a886-455a-914f-2dd64b1fe222.png">

It would be nice if the deployment created for this PR would be shown directly in the PR.

**Comment by peschee** [comment]
This works for some action runs in PRs, so I think we might be running into #29 here.

**Comment by WalshyDev** [comment]
What's the rest of your config? This will work if it's being fired but seems like it isn't. I'd check your config and make sure this actually being ran on PRs

**Comment by peschee** [comment]
@WalshyDev 

```yaml
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
```
