### ISSUE TITLE
Error: Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by rk-p2p** [cloudflare/pages-action#41]
Hi! There is a bug with v1.2.0
`Error: Parameter token or opts.auth is required`
My workflow's step:
```
...
      - name: publish
        uses: cloudflare/pages-action@v1.2.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: xxx
          directory: .
          # Optional: Enable this if you want to have GitHub Deployments triggered
          #gitHubToken: ${{ secrets.GITHUB_TOKEN }}
...
```
