### ISSUE TITLE
Bug: "branch" input bug in v1.4.0

### ISSUE THREAD

**Issue by aantipov** [cloudflare/pages-action#67]
Latest `v1.4.0` introduced changes to how "branch" prop is handled https://github.com/cloudflare/pages-action/pull/56/files

It broke our deployment pipelines in all our projects with "RequestError [HttpError]: No ref found for" error:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/427621/224002305-0c3ee847-83b5-43b5-a51f-f5a29bcd5668.png">

As you notice here, when the action sends request to Github to create a new deployment object, the `ref` prop is empty
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/427621/224002468-709eb054-4c88-4c31-8ca9-29661dc20da6.png">

Deployment is triggered by a `pull_request`

**Hot Fix**: specifying `v1.3.0` fixed the issue

**Comment by krisgardiner** [comment]
Updating to `cloudflare/pages-action@v1` worked for me.

**Comment by WalshyDev** [comment]
We just reverted the commit for this, and will release v1.4.1 now.

**Comment by aaronadamsCA** [comment]
@aantipov Could you please share the action inputs you were passing to the action when you encountered this error?

I'm trying to figure out how to reproduce this. I contributed #56 specifically so `pull_request` events would get the correct ref, and it works for me, but obviously failed for a bunch of other people, so I'd like to figure out why.

**Comment by aaronadamsCA** [comment]
CC @jkorichneva, @felixlublasser, @ivolimasilva, @limakzi, @tamacti - same as above, if you could please share your GitHub Actions workflow where you encountered this issue, I'm trying to reproduce your error so I can fix the original PR.

**Comment by ivolimasilva** [comment]
I'm using Cloudflare Pages to deploy a version of a web app on every PR, where we pass a custom `branch` to match the project + PR's number. Here's the workflow using `cloudflare/pages-action`:

```yaml
on:
  pull_request:

# ...

jobs:
  # ...
  - id: deploy
    name: Deploy `client` to preview environment
    uses: cloudflare/pages-action@v1
    with:
      apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      projectName: ${{ secrets.PROJECT_NAME }}
      directory: ./apps/client/build
      gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      branch: "client-pr${{ github.event.pull_request.number }}"
    env:
      GITHUB_TOKEN: ${{ github.token }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
```

And the error would be:
```
/home/runner/work/_actions/cloudflare/pages-action/v1/index.js:5857
          const error = new requestError.RequestError(toErrorMessage(data), status, {
                        ^

RequestError [HttpError]: No ref found for: client-pr123
```
