### ISSUE TITLE
error npx: command not found

### ISSUE THREAD

**Issue by RodrigoDornelles** [cloudflare/pages-action#74]
not working inside of container action :/

```
with:
    apiToken: ***
    accountId: ***
    projectName: doxygen-[3](https://github.com/RodrigoDornelles/3bc-lang/actions/runs/4518829344/jobs/7958944351#step:5:3)bc
    directory: html
    gitHubToken: ***
/usr/bin/docker exec  90eb791a8e9e29532bfdb63bc7[4](https://github.com/RodrigoDornelles/3bc-lang/actions/runs/4518829344/jobs/7958944351#step:5:4)[5](https://github.com/RodrigoDornelles/3bc-lang/actions/runs/4518829344/jobs/7958944351#step:5:5)ea51bb05c3f87cb3189488e7[6](https://github.com/RodrigoDornelles/3bc-lang/actions/runs/4518829344/jobs/7958944351#step:5:6)[7](https://github.com/RodrigoDornelles/3bc-lang/actions/runs/4518829344/jobs/7958944351#step:5:7)7725[9](https://github.com/RodrigoDornelles/3bc-lang/actions/runs/4518829344/jobs/7958944351#step:5:10)026ff sh -c "cat /etc/*release | grep ^ID"
bash: line 6: npx: command not found
EXIT WHEN NOT EXPECTED

SHELLAC COMMAND FAILED!
Executing: npx wrangler@2 pages publish "html" --project-name="doxygen-3bc" --branch="" in /__w/3bc-lang/3bc-lang

STDOUT:



STDERR:

bash: line 6: npx: command not found


node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by RealRTTV** [comment]
Encountering the same issue, any updates?

**Comment by RealRTTV** [comment]
workflow file:
```yaml
name: Compile and Publish Web Assembly Edition

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  wasm:
    runs-on: windows-latest

    steps:
      - name: disable git eol translation
        run: git config --global core.autocrlf false
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: |
          node -v
          npx --yes wrangler@3.28.2

      - name: Install Rustup using win.rustup.rs
        run: |
          # Disable the download progress bar which can cause perf issues
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
          .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=nightly
          del rustup-init.exe
          rustup target add x86_64-pc-windows-msvc --toolchain nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
        shell: powershell

      - name: Add mingw64 to path for x86_64-msvc
        shell: bash
        run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

      - name: Add wasm-pack
        shell: cmd
        run: cargo install wasm-pack

      - name: Build
        shell: cmd
        run: wasm-pack build --release --target web --out-dir nbtworkbench

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: 'nbtworkbench'
          directory: .
          workingDirectory: './web'
          wranglerVersion: 3.28.2
```
