### ISSUE TITLE
Deprecation warning about `wrangler pages publish`

### ISSUE THREAD

**Issue by brycewray** [cloudflare/pages-action#88]
When I run this action, it works but I get this error message in the log:

```bash
▲ [WARNING] `wrangler pages publish` is deprecated and will be removed in the next major version.

  Please use `wrangler pages deploy` instead, which accepts exactly the same arguments.
```

This is the relevant part of my overall workflow file:

```yaml
      - name: Publish to CFP (cond. - host = CFP)
        if: ${{ env.HOST == 'CFP' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CFP_API_TOKEN }}
          accountID: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'static-site-v2' # was 'static-site' (now 'static-site-old')
          directory: 'public'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3' # enable Wrangler v3
```

. . . although I was seeing this before I added the `wranglerVersion` line to the `with` section.

Does the deprecation warning mean I need to pass some additional args?
