### ISSUE TITLE
The branch parameter is not defaulted to the branch that triggers a workflow

### ISSUE THREAD

**Issue by apeacock1991** [cloudflare/pages-action#97]
Based on the documentation, if you omit branch, it should default to the branch for the workflow.

I omitted the parameter, but it always reported deployments in the dashboard to master. Passing the branch using `branch: ${{ github.ref_name }}` fixed this, but the docs either need updating or the code fixing.

**Comment by davidlj95** [comment]
Addition to OP:

`github.ref_name` in a pull request refers to the [pull request merge branch](https://fluffyandflakey.blog/2022/12/21/what-is-a-github-pull-request-merge-branch/). Something like `42/merge`. Where `42` is the PR number.

So instead, I've used:

```
branch:  ${{ github.head_ref || github.ref }}
```

`github.head_ref` refers to the base branch if being triggered in a pull request (i.e. `feat-do-some-work`). And if not a pull request, assume it's a `push` workflow and then `github.ref` is the branch that was pushed (i.e. `main`)

**Comment by davidlj95** [comment]
Btw I'm using [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows). 

I think that's the source of the issue. Given the action [tries to get branch name from env vars `GITHUB_HEAD_REF` or `GITHUB_REF_NAME`](https://github.com/cloudflare/pages-action/blob/v1.5.0/src/index.ts#L63). And when using reusable workflows, [the called workflow doesn't have access to those](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations:~:text=env%20context%20defined%20at%20the%20workflow%20level%20in%20the%20caller%20workflow%20are%20not%20propagated%20to%20the%20called%20workflow) unless you manually pass those env vars.

So guess another workaround could also be to pass those manually when calling the reusable workflow:

```yml
  deploy-preview:
    name: Deploy preview
    uses: ./.github/workflows/reusable-deploy-cloudflare-pages.yml
    env:
      GITHUB_HEAD_REF: {{ github.head_ref }}
      GITHUB_REF: {{ github. ref }}
```
